name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy Files to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            scp -i ${{ secrets.EC2_KEY }} -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

      # - name: Notify Deployment
      #   uses: dawidd6/action-send-message@v2
      #   with:
      #     args: "Deployment to EC2 completed successfully."
      #   env:
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

